name: affinity-internship
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.13.5
  - requests=2.32.5
  - beautifulsoup4=4.13.5
  - lxml=6.0.1
  - pandas=2.3.1
  - numpy=2.2.5
  - pip=25.2
  - pip:
    - selenium == 4.15.0